### ISSUE TITLE
does not work when nextcloud in subdir

### ISSUE THREAD

**Issue by r2evans** [nextcloud/nextcloud-filelink#26] opened 2017-06-15 23:21 UTC
## Bug report

Unable to connect to server when the domain includes a subdir path.

I believe the problem is that the script concatenates `this._serverUrl + ":" + this._serverPort`. (See the Thunderbird log below, it clearly shows the malformed URI.)

Suggestion, either:

1. Remove the field to type in the port number, regex-ing it out or assuming that URI defaults will suffice; this requires the user to manually add non-standard ports (which is a safe default, IMO);
2. Add another field, "nextcloud directory installation", so my config would be: domain `https://mydomain.com`, port `443`, subdir `/cloud`.

I hacked the code and removed all references to `+ ":" + _serverPort` in `src/components/nsNextcloud.js`, and I was able to configure the connection. It was a hack and I'm having other issues, but this hack got me past the account setup.

### Steps to reproduce

1. Install nextcloud in a subdir, e.g., `https://mydomain.com/nc/`
1. Configure nextcloud-filelink with domain `https://mydomain.com/nc` and port `443`

### Expected behaviour

Network connection made to the server, authentication passes, filelink account created.

### Actual behaviour

No connection is made with the server (logs show no attempt).

### Server configuration

**Operating system**: ubuntu-16.04.4

**Web server**: nginx-1.10.3-0+trusty0

**Database:** pg

**PHP version:** php-7.0

**Nextcloud version:** 11.0.3.2

**Updated from an older installation or fresh install:** fresh

**List of activated apps:**

<details>
<summary>App list</summary>

```
$ sudo -u www-data php occ app:list
Enabled:
  - activity: 2.4.1
  - admin_audit: 1.1.0
  - calendar: 1.5.3
  - comments: 1.1.0
  - contacts: 1.5.3
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_retention: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - user_ldap: 1.1.2
  - workflowengine: 1.1.1
Disabled:
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - user_external
  - user_saml
```

</details>

**The content of config/config.php:**

<details>
<summary>Config report</summary>

```
# sudo -u www-data php occ config:list system
{
    "system": {
        "redis": {
            "host": "redis",
            "port": 6379
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "mydomain.com"
        ],
        "datadirectory": "\/var\/lib\/nextcloud\/ocdata",
        "overwrite.cli.url": "https:\/\/mydomain.com\/cloud",
        "dbtype": "pgsql",
        "version": "11.0.3.2",
        "dbname": "nextcloud_db",
        "dbhost": "postgresql:5432",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "instanceid": "...",
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "smtpout.secureserver.net",
        "mail_smtpport": "465",
        "mail_from_address": "admin",
        "mail_domain": "mydomain.com",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpsecure": "ssl",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "ldapIgnoreNamingRules": false,
        "appstore.experimental.enabled": true,
        "loglevel": 1,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory"
    }
}
```

</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

#### Web server error log

<details>
<summary>Web server error log</summary>

```
(nothing)
```
</details>

#### Cloud log

<details>
<summary>Nextcloud log</summary>

```
(nothing)
```
</details>

### Desktop configuration

**Operating system**: Win10_64

**Thunderbird version:** 52.2.0

**Updated from an older installation or fresh install:** updated

#### Thunderbird Log

<details>
<summary>Thunderbird log</summary>

```
GET 
XHR 
https://mydomain.com/cloud:443/ocs/v1.php/cloud/user [HTTP/1.1 204 No Content 27ms]
Headers
Params
Response
Call Stack
Connectionkeep-aliveDateThu, 15 Jun 2017 22:13:07 GMTServernginx/1.10.3
Accept*/*Accept-Encodinggzip, deflate, brAccept-Languageen-US,en;q=0.5AuthorizationBasic snip=Connectionkeep-aliveContent-Typeapplication/x-www-form-urlencodedHostmydomain.comOCS-APIREQUESTtrueUser-AgentMozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Thunderbird/52.2.0 Lightning/5.4.2

2017-06-15 15:13:07	Nextcloud	ERROR	SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
```

</details>

**Comment by oparoz** [comment] 2017-06-15 23:56
Thanks for the report. It's a duplicate of https://github.com/nextcloud/nextcloud-filelink/issues/21

**Closed by oparoz** 2017-06-15 23:56 UTC

**Comment by r2evans** [comment] 2017-06-15 23:57
Oh crap, I mis-read that, sorry.

**Comment by oparoz** [comment] 2017-06-16 00:01
Well, it's more that the title of that issue does not describe it very well ;)
I've renamed it.
